format = """$character"""
right_format = """$directory$time$git_branch$git_status"""

[ruby]
symbol = " "

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)](purple) '
symbol = " "
truncation_length = 11

[nodejs]
symbol = '󰎙 '

[lua]
symbol = ' '

[time]
disabled = false
time_format = "󰥔 %k:%m"

[directory]
truncation_length = 2

[git_status]
format = '(\[$all_status$ahead_behind\] )'
conflicted = ''
ahead = ''
behind = ''
diverged = '󱡷'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!'
staged = '[++\($count\)](green)'
renamed = '󰑙'
deleted = ''

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"
vimcmd_symbol = "[ ](bold green)"
vimcmd_replace_symbol = "[ ](bold yellow)"
vimcmd_visual_symbol = "[ ](bold purple)"
